/*import styles from '@/styles/Home.module.css'*/
import Head from "next/head"
import {getTenMovies} from "@/API/ombdApi";

import {MovieList as MovieListInterface, MovieLists, SearchResult} from "@/interfaces/interfaces";
import MovieList from "@/components/home/movieList";

export default function ListMovies({movieLists}: MovieLists) {

    return (
        <>
            <Head>
                <title>Netflix Clone</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1>Challenge project</h1>
                {movieLists.map(
                    (movieList: MovieListInterface, index: number) => <MovieList {...{movieList}} key={index} />
                )}
            </main>
        </>
    )
}


export async function getStaticProps() {
    const tenMoviesStar: SearchResult[] | string = await getTenMovies(1, 'star')
    const tenMoviesCat: SearchResult[] | string = await getTenMovies(1, 'cat')

    const MoviesAboutStar: MovieListInterface = {
        title: 'Star',
        movies: tenMoviesStar
    }

    const MoviesAboutCat: MovieListInterface = {
        title: 'Cat',
        movies: tenMoviesCat
    }

    return {
        props: {
            movieLists: [
                MoviesAboutStar,
                MoviesAboutCat
            ]
        },
        revalidate: 3600 // revalidate if there are requests
    };
}
